### PR TITLE
Add krontab and ktgbotapi libraries

### PR DESCRIPTION
**Pull request by InsanusMokrassar**

### CODE REVIEW

**Comment by terrakok** [comment]
Does it support ios and android targets?

**Comment by InsanusMokrassar** [comment]
No, it support android, jvm, js, linuxX64 and mingwX64

**Comment by terrakok** [comment]
Waiting ios support and will be glad to add it to the list)

**Comment by InsanusMokrassar** [comment]
> Waiting ios support and will be glad to add it to the list)

Got it. Unfortunatelly, I dont think these libraries will take ios support :(

**Pull request closed without merging**
