### PR TITLE
Add KCron library

### PR DESCRIPTION
**Pull request by Scogun**

### CODE REVIEW

**Comment by Scogun** [comment]
Hello @terrakok! Could you check the PR?

**Comment by terrakok** [comment]
https://github.com/terrakok/kmp-awesome#contribution-guide

**Comment by Scogun** [comment]
So, it has 22 stars. I see there is a librarie with 14.
It is published on Maven.
It has Android and iOS targets. 
At least two more projects use it. 
Is it still not enough?

**Comment by terrakok** [comment]
next time provide the external projects which uses the library, please

**Comment by Scogun** [comment]
Sorry, just wrote me previous comment from a phone and wasn't able to find links to provide them. Here they are:
https://github.com/pvanassen/led-controller
https://github.com/mgroth0/time
https://github.com/vchain-dev/kotask

**Pull request merged**
