### PR TITLE
Add `partial-json-parser-kmp`

### PR DESCRIPTION
**Pull request by FunnySaltyFish**
It's a library to help parse incomplete JSON (like what ChatGPT generates in stream mode) in Kotlin, obtain information as much as possible.

Examples:
```kotlin
val partialJson = "{\"key\":\"Hello, "
val map = PartialJsonParser.parse(partialJson) as? Map<*, *> // Map(key=Hello, )
println(map) // {key=Hello, }
println(map?.get("key")) // Hello,
```

More:
```
{"ke                      -> {}
{"key"                    -> {}
{"key":                   -> {}
{"key":"te                -> {key=te}
{"key":"text", "key2      -> {key=text}
{"key":"text", "key2":"t} -> {key=text, key2=t}}

{"k":[1,2,3               -> {k=[1.0, 2.0, 3.0]}
{"k":[[1,2                -> {k=[[1.0, 2.0]]}
{"k":[[1,2],["v"          -> {k=[[1.0, 2.0], [v]]}
{"k":{"k2":1              -> {k={k2=1.0}}
{"k":{"k2":1, "k3":2      -> {k={k2=1.0, k3=2.0}}
{"k":{"k2":1, "k3":       -> {k={k2=1.0}}
{"k":[{"k2":1, "k3":2     -> {k=[{k2=1.0, k3=2.0}]}
```

> https://github.com/FunnySaltyFish/partial-json-parser-kmp

### CODE REVIEW

**Comment by terrakok** [comment]
Is there at least one external open source app which uses the library?

**Comment by FunnySaltyFish** [comment]
As far as I know, not yet. The library was just finished one week ago. One of my applications uses the library but the relevant codes are not open source yet. I don't know where to publicize, maybe I can wait for some time.

**Comment by terrakok** [comment]
Well, I guess it is too early to add to the library to the awesome list. do you agree?

**Comment by FunnySaltyFish** [comment]
Ok, it can help maintain the quality of the list, I agree. However, may I ask you to please keep this PR open for some time? Maybe passer-by can know it by this way. I will close it if no one uses it after some time.

**Comment by terrakok** [comment]
Sure, it can be opened as long as you want

**Comment by terrakok** [comment]
https://github.com/terrakok/kmp-awesome#contribution-guide

**Comment by FunnySaltyFish** [comment]
Got it, I'll close the PR.

**Pull request closed without merging**
